version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_wordpress
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    ports:
      - "8000:80"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
  wordpress_data:
